/// {@template iconex_flutter}
/// A Flutter package that provides access to the **Iconex** icon set —
/// clean, consistent vector icons for modern interfaces.
///
/// Each icon style (Filled, Light, Broken) can be accessed using
/// the [`Iconex`] class:
///
/// ```dart
/// Icon(Iconex.filled.home);
/// Icon(Iconex.light.search);
/// Icon(Iconex.broken.heart);
/// ```
///
/// The icons are based on the open-source **Iconex** collection
/// by [Dmitry Mikhaylov](https://dribbble.com/MikhaylovArt)
/// and [Tatyana Sheplyakova](https://dribbble.com/TatyanaShe).
///
/// {@endtemplate}
library;

import 'package:flutter/widgets.dart';

part 'generated/iconex_broken.dart';
part 'generated/iconex_filled.dart';
part 'generated/iconex_light.dart';

/// Provides access to all **Iconex** icon styles (Filled, Light, Broken).
///
/// ```dart
/// Icon(Iconex.filled.home);
/// Icon(Iconex.light.search);
/// Icon(Iconex.broken.heart);
/// ```
///
/// Each style exposes the same set of icon names.
class Iconex {
  /// Private constructor. Use [Iconex.filled], [Iconex.light], or [Iconex.broken].
  Iconex._();

  /// Filled icon style — solid shapes for bold designs.
  static const filled = _IconexFilled();

  /// Light icon style — outlined shapes for minimal UIs.
  static const light = _IconexLight();

  /// Broken icon style — creative broken-line style icons.
  static const broken = _IconexBroken();
}

class _IconexFilled {
  const _IconexFilled();

  IconData get infoSquare => _IconexFilledData.infoSquare;
  IconData get lightning => _IconexFilledData.lightning;
  IconData get search => _IconexFilledData.search;
  IconData get timeSquare => _IconexFilledData.timeSquare;
  IconData get receipt => _IconexFilledData.receipt;
  IconData get leftCircle => _IconexFilledData.leftCircle;
  IconData get figma => _IconexFilledData.figma;
  IconData get upRightCircle => _IconexFilledData.upRightCircle;
  IconData get shield2 => _IconexFilledData.shield2;
  IconData get box1 => _IconexFilledData.box1;
  IconData get chart1 => _IconexFilledData.chart1;
  IconData get lockCheck => _IconexFilledData.lockCheck;
  IconData get downLeft => _IconexFilledData.downLeft;
  IconData get bag1 => _IconexFilledData.bag1;
  IconData get bag3 => _IconexFilledData.bag3;
  IconData get chart => _IconexFilledData.chart;
  IconData get box2 => _IconexFilledData.box2;
  IconData get shield1 => _IconexFilledData.shield1;
  IconData get user => _IconexFilledData.user;
  IconData get bag2 => _IconexFilledData.bag2;
  IconData get volumeUp => _IconexFilledData.volumeUp;
  IconData get home => _IconexFilledData.home;
  IconData get moreCircle => _IconexFilledData.moreCircle;
  IconData get category2 => _IconexFilledData.category2;
  IconData get music => _IconexFilledData.music;
  IconData get filter2 => _IconexFilledData.filter2;
  IconData get swap2 => _IconexFilledData.swap2;
  IconData get logout => _IconexFilledData.logout;
  IconData get upSquare => _IconexFilledData.upSquare;
  IconData get right2 => _IconexFilledData.right2;
  IconData get documentAdd => _IconexFilledData.documentAdd;
  IconData get downSquare => _IconexFilledData.downSquare;
  IconData get down => _IconexFilledData.down;
  IconData get lockX => _IconexFilledData.lockX;
  IconData get upRight => _IconexFilledData.upRight;
  IconData get caseIcon => _IconexFilledData.caseIcon;
  IconData get swap3 => _IconexFilledData.swap3;
  IconData get creditCard => _IconexFilledData.creditCard;
  IconData get cloudDownload => _IconexFilledData.cloudDownload;
  IconData get messageCircle => _IconexFilledData.messageCircle;
  IconData get downSquare2 => _IconexFilledData.downSquare2;
  IconData get filter1 => _IconexFilledData.filter1;
  IconData get microphone => _IconexFilledData.microphone;
  IconData get toggleRight => _IconexFilledData.toggleRight;
  IconData get down2 => _IconexFilledData.down2;
  IconData get zoomIn => _IconexFilledData.zoomIn;
  IconData get rightSquare2 => _IconexFilledData.rightSquare2;
  IconData get document2 => _IconexFilledData.document2;
  IconData get upCircle1 => _IconexFilledData.upCircle1;
  IconData get up => _IconexFilledData.up;
  IconData get alarmClock => _IconexFilledData.alarmClock;
  IconData get lock => _IconexFilledData.lock;
  IconData get fire => _IconexFilledData.fire;
  IconData get edit2 => _IconexFilledData.edit2;
  IconData get link => _IconexFilledData.link;
  IconData get key => _IconexFilledData.key;
  IconData get cloudUpload => _IconexFilledData.cloudUpload;
  IconData get settings => _IconexFilledData.settings;
  IconData get cart => _IconexFilledData.cart;
  IconData get edit1 => _IconexFilledData.edit1;
  IconData get mail => _IconexFilledData.mail;
  IconData get addUser => _IconexFilledData.addUser;
  IconData get shield => _IconexFilledData.shield;
  IconData get expand => _IconexFilledData.expand;
  IconData get up2 => _IconexFilledData.up2;
  IconData get upLeft => _IconexFilledData.upLeft;
  IconData get upSquare2 => _IconexFilledData.upSquare2;
  IconData get sale => _IconexFilledData.sale;
  IconData get layers => _IconexFilledData.layers;
  IconData get login => _IconexFilledData.login;
  IconData get book => _IconexFilledData.book;
  IconData get collapse => _IconexFilledData.collapse;
  IconData get rightCircle => _IconexFilledData.rightCircle;
  IconData get wallet => _IconexFilledData.wallet;
  IconData get bell => _IconexFilledData.bell;
  IconData get logout1 => _IconexFilledData.logout1;
  IconData get coffee => _IconexFilledData.coffee;
  IconData get flag => _IconexFilledData.flag;
  IconData get trashCan => _IconexFilledData.trashCan;
  IconData get stop => _IconexFilledData.stop;
  IconData get category => _IconexFilledData.category;
  IconData get plus => _IconexFilledData.plus;
  IconData get document => _IconexFilledData.document;
  IconData get filter1_2 => _IconexFilledData.filter1_2;
  IconData get check => _IconexFilledData.check;
  IconData get headphones => _IconexFilledData.headphones;
  IconData get calling => _IconexFilledData.calling;
  IconData get left2 => _IconexFilledData.left2;
  IconData get downCircle1 => _IconexFilledData.downCircle1;
  IconData get lockOpen => _IconexFilledData.lockOpen;
  IconData get scale => _IconexFilledData.scale;
  IconData get close => _IconexFilledData.close;
  IconData get coupon2 => _IconexFilledData.coupon2;
  IconData get callMissed => _IconexFilledData.callMissed;
  IconData get copy => _IconexFilledData.copy;
  IconData get burger => _IconexFilledData.burger;
  IconData get coins => _IconexFilledData.coins;
  IconData get volumeDown => _IconexFilledData.volumeDown;
  IconData get hide => _IconexFilledData.hide;
  IconData get infoCircle => _IconexFilledData.infoCircle;
  IconData get image => _IconexFilledData.image;
  IconData get timeCircle => _IconexFilledData.timeCircle;
  IconData get leftSquare => _IconexFilledData.leftSquare;
  IconData get save => _IconexFilledData.save;
  IconData get callSilent => _IconexFilledData.callSilent;
  IconData get leftSquare2 => _IconexFilledData.leftSquare2;
  IconData get right => _IconexFilledData.right;
  IconData get coupon3 => _IconexFilledData.coupon3;
  IconData get upLeftCircle => _IconexFilledData.upLeftCircle;
  IconData get coupon1 => _IconexFilledData.coupon1;
  IconData get leftCircle1 => _IconexFilledData.leftCircle1;
  IconData get paperclip => _IconexFilledData.paperclip;
  IconData get loading => _IconexFilledData.loading;
  IconData get noSoundMicrophone => _IconexFilledData.noSoundMicrophone;
  IconData get moreSquare => _IconexFilledData.moreSquare;
  IconData get play => _IconexFilledData.play;
  IconData get downRightCircle => _IconexFilledData.downRightCircle;
  IconData get send => _IconexFilledData.send;
  IconData get camera => _IconexFilledData.camera;
  IconData get toggleLeft => _IconexFilledData.toggleLeft;
  IconData get upCircle => _IconexFilledData.upCircle;
  IconData get star => _IconexFilledData.star;
  IconData get downCircle => _IconexFilledData.downCircle;
  IconData get danger => _IconexFilledData.danger;
  IconData get browser => _IconexFilledData.browser;
  IconData get messageSquare => _IconexFilledData.messageSquare;
  IconData get compass => _IconexFilledData.compass;
  IconData get basketball => _IconexFilledData.basketball;
  IconData get musicPlate => _IconexFilledData.musicPlate;
  IconData get call => _IconexFilledData.call;
  IconData get link2 => _IconexFilledData.link2;
  IconData get eye => _IconexFilledData.eye;
  IconData get location => _IconexFilledData.location;
  IconData get rightCircle1 => _IconexFilledData.rightCircle1;
  IconData get gift => _IconexFilledData.gift;
  IconData get colorPalette => _IconexFilledData.colorPalette;
  IconData get share => _IconexFilledData.share;
  IconData get video => _IconexFilledData.video;
  IconData get filter => _IconexFilledData.filter;
  IconData get oldschoolGamepad => _IconexFilledData.oldschoolGamepad;
  IconData get calendar => _IconexFilledData.calendar;
  IconData get laptop => _IconexFilledData.laptop;
  IconData get heartbeat => _IconexFilledData.heartbeat;
  IconData get scanner => _IconexFilledData.scanner;
  IconData get cloud => _IconexFilledData.cloud;
  IconData get pause => _IconexFilledData.pause;
  IconData get bookmark => _IconexFilledData.bookmark;
  IconData get rocket => _IconexFilledData.rocket;
  IconData get screen => _IconexFilledData.screen;
  IconData get iphone => _IconexFilledData.iphone;
  IconData get volumeOff1 => _IconexFilledData.volumeOff1;
  IconData get rightSquare => _IconexFilledData.rightSquare;
  IconData get download2 => _IconexFilledData.download2;
  IconData get downRight => _IconexFilledData.downRight;
  IconData get calculator => _IconexFilledData.calculator;
  IconData get mouse => _IconexFilledData.mouse;
  IconData get zoomOut => _IconexFilledData.zoomOut;
  IconData get graph => _IconexFilledData.graph;
  IconData get folder => _IconexFilledData.folder;
  IconData get users => _IconexFilledData.users;
  IconData get left => _IconexFilledData.left;
  IconData get timer => _IconexFilledData.timer;
  IconData get gamepad => _IconexFilledData.gamepad;
  IconData get minus => _IconexFilledData.minus;
  IconData get downLeftCircle => _IconexFilledData.downLeftCircle;
  IconData get documentDelete => _IconexFilledData.documentDelete;
  IconData get swap => _IconexFilledData.swap;
  IconData get volumeOff2 => _IconexFilledData.volumeOff2;
  IconData get heart => _IconexFilledData.heart;
}

class _IconexLight {
  const _IconexLight();

  IconData get infoSquare => _IconexLightData.infoSquare;
  IconData get lightning => _IconexLightData.lightning;
  IconData get search => _IconexLightData.search;
  IconData get timeSquare => _IconexLightData.timeSquare;
  IconData get receipt => _IconexLightData.receipt;
  IconData get leftCircle => _IconexLightData.leftCircle;
  IconData get figma => _IconexLightData.figma;
  IconData get upRightCircle => _IconexLightData.upRightCircle;
  IconData get shield2 => _IconexLightData.shield2;
  IconData get box1 => _IconexLightData.box1;
  IconData get chart1 => _IconexLightData.chart1;
  IconData get lockCheck => _IconexLightData.lockCheck;
  IconData get downSquare1 => _IconexLightData.downSquare1;
  IconData get downLeft => _IconexLightData.downLeft;
  IconData get bag1 => _IconexLightData.bag1;
  IconData get bag3 => _IconexLightData.bag3;
  IconData get chart => _IconexLightData.chart;
  IconData get box2 => _IconexLightData.box2;
  IconData get shield1 => _IconexLightData.shield1;
  IconData get box3 => _IconexLightData.box3;
  IconData get user => _IconexLightData.user;
  IconData get chart2 => _IconexLightData.chart2;
  IconData get bag2 => _IconexLightData.bag2;
  IconData get volumeUp => _IconexLightData.volumeUp;
  IconData get home => _IconexLightData.home;
  IconData get moreCircle => _IconexLightData.moreCircle;
  IconData get category2 => _IconexLightData.category2;
  IconData get bag6 => _IconexLightData.bag6;
  IconData get music => _IconexLightData.music;
  IconData get swap2 => _IconexLightData.swap2;
  IconData get logout => _IconexLightData.logout;
  IconData get upSquare => _IconexLightData.upSquare;
  IconData get right2 => _IconexLightData.right2;
  IconData get documentAdd => _IconexLightData.documentAdd;
  IconData get downSquare => _IconexLightData.downSquare;
  IconData get down => _IconexLightData.down;
  IconData get lockX => _IconexLightData.lockX;
  IconData get upRight => _IconexLightData.upRight;
  IconData get caseIcon => _IconexLightData.caseIcon;
  IconData get swap3 => _IconexLightData.swap3;
  IconData get creditCard => _IconexLightData.creditCard;
  IconData get cloudDownload => _IconexLightData.cloudDownload;
  IconData get category3 => _IconexLightData.category3;
  IconData get bag5 => _IconexLightData.bag5;
  IconData get messageCircle => _IconexLightData.messageCircle;
  IconData get downSquare2 => _IconexLightData.downSquare2;
  IconData get microphone => _IconexLightData.microphone;
  IconData get toggleRight => _IconexLightData.toggleRight;
  IconData get down2 => _IconexLightData.down2;
  IconData get zoomIn => _IconexLightData.zoomIn;
  IconData get document3 => _IconexLightData.document3;
  IconData get box4 => _IconexLightData.box4;
  IconData get rightSquare2 => _IconexLightData.rightSquare2;
  IconData get document2 => _IconexLightData.document2;
  IconData get bag4 => _IconexLightData.bag4;
  IconData get upCircle1 => _IconexLightData.upCircle1;
  IconData get up => _IconexLightData.up;
  IconData get alarmClock => _IconexLightData.alarmClock;
  IconData get lock => _IconexLightData.lock;
  IconData get search1 => _IconexLightData.search1;
  IconData get fire => _IconexLightData.fire;
  IconData get edit2 => _IconexLightData.edit2;
  IconData get edit3 => _IconexLightData.edit3;
  IconData get link => _IconexLightData.link;
  IconData get key => _IconexLightData.key;
  IconData get cloudUpload => _IconexLightData.cloudUpload;
  IconData get settings => _IconexLightData.settings;
  IconData get cart => _IconexLightData.cart;
  IconData get edit1 => _IconexLightData.edit1;
  IconData get mail => _IconexLightData.mail;
  IconData get addUser => _IconexLightData.addUser;
  IconData get shield => _IconexLightData.shield;
  IconData get expand => _IconexLightData.expand;
  IconData get up2 => _IconexLightData.up2;
  IconData get upLeft => _IconexLightData.upLeft;
  IconData get upSquare2 => _IconexLightData.upSquare2;
  IconData get sale => _IconexLightData.sale;
  IconData get layers => _IconexLightData.layers;
  IconData get login => _IconexLightData.login;
  IconData get book => _IconexLightData.book;
  IconData get collapse => _IconexLightData.collapse;
  IconData get rightCircle => _IconexLightData.rightCircle;
  IconData get wallet => _IconexLightData.wallet;
  IconData get edit4 => _IconexLightData.edit4;
  IconData get bell => _IconexLightData.bell;
  IconData get logout1 => _IconexLightData.logout1;
  IconData get coffee => _IconexLightData.coffee;
  IconData get flag => _IconexLightData.flag;
  IconData get trashCan => _IconexLightData.trashCan;
  IconData get stop => _IconexLightData.stop;
  IconData get category => _IconexLightData.category;
  IconData get plus => _IconexLightData.plus;
  IconData get document => _IconexLightData.document;
  IconData get filter1 => _IconexLightData.filter1;
  IconData get check => _IconexLightData.check;
  IconData get headphones => _IconexLightData.headphones;
  IconData get calling => _IconexLightData.calling;
  IconData get left2 => _IconexLightData.left2;
  IconData get downCircle1 => _IconexLightData.downCircle1;
  IconData get lockOpen => _IconexLightData.lockOpen;
  IconData get scale => _IconexLightData.scale;
  IconData get close => _IconexLightData.close;
  IconData get coupon2 => _IconexLightData.coupon2;
  IconData get callMissed => _IconexLightData.callMissed;
  IconData get copy => _IconexLightData.copy;
  IconData get burger => _IconexLightData.burger;
  IconData get coins => _IconexLightData.coins;
  IconData get volumeDown => _IconexLightData.volumeDown;
  IconData get hide => _IconexLightData.hide;
  IconData get infoCircle => _IconexLightData.infoCircle;
  IconData get image => _IconexLightData.image;
  IconData get timeCircle => _IconexLightData.timeCircle;
  IconData get leftSquare => _IconexLightData.leftSquare;
  IconData get save => _IconexLightData.save;
  IconData get callSilent => _IconexLightData.callSilent;
  IconData get leftSquare2 => _IconexLightData.leftSquare2;
  IconData get right => _IconexLightData.right;
  IconData get coupon3 => _IconexLightData.coupon3;
  IconData get upLeftCircle => _IconexLightData.upLeftCircle;
  IconData get coupon1 => _IconexLightData.coupon1;
  IconData get leftCircle1 => _IconexLightData.leftCircle1;
  IconData get paperclip => _IconexLightData.paperclip;
  IconData get loading => _IconexLightData.loading;
  IconData get noSoundMicrophone => _IconexLightData.noSoundMicrophone;
  IconData get moreSquare => _IconexLightData.moreSquare;
  IconData get play => _IconexLightData.play;
  IconData get downRightCircle => _IconexLightData.downRightCircle;
  IconData get send => _IconexLightData.send;
  IconData get camera => _IconexLightData.camera;
  IconData get coupon4 => _IconexLightData.coupon4;
  IconData get toggleLeft => _IconexLightData.toggleLeft;
  IconData get upCircle => _IconexLightData.upCircle;
  IconData get star => _IconexLightData.star;
  IconData get downCircle => _IconexLightData.downCircle;
  IconData get coupon5 => _IconexLightData.coupon5;
  IconData get danger => _IconexLightData.danger;
  IconData get browser => _IconexLightData.browser;
  IconData get messageSquare => _IconexLightData.messageSquare;
  IconData get compass => _IconexLightData.compass;
  IconData get coupon6 => _IconexLightData.coupon6;
  IconData get basketball => _IconexLightData.basketball;
  IconData get musicPlate => _IconexLightData.musicPlate;
  IconData get call => _IconexLightData.call;
  IconData get link2 => _IconexLightData.link2;
  IconData get eye => _IconexLightData.eye;
  IconData get link3 => _IconexLightData.link3;
  IconData get location => _IconexLightData.location;
  IconData get rightCircle1 => _IconexLightData.rightCircle1;
  IconData get gift => _IconexLightData.gift;
  IconData get colorPalette => _IconexLightData.colorPalette;
  IconData get share => _IconexLightData.share;
  IconData get video => _IconexLightData.video;
  IconData get filter => _IconexLightData.filter;
  IconData get oldschoolGamepad => _IconexLightData.oldschoolGamepad;
  IconData get calendar => _IconexLightData.calendar;
  IconData get volumeOff4 => _IconexLightData.volumeOff4;
  IconData get laptop => _IconexLightData.laptop;
  IconData get heartbeat => _IconexLightData.heartbeat;
  IconData get scanner => _IconexLightData.scanner;
  IconData get cloud => _IconexLightData.cloud;
  IconData get download3 => _IconexLightData.download3;
  IconData get pause => _IconexLightData.pause;
  IconData get bookmark => _IconexLightData.bookmark;
  IconData get rocket => _IconexLightData.rocket;
  IconData get screen => _IconexLightData.screen;
  IconData get iphone => _IconexLightData.iphone;
  IconData get volumeOff1 => _IconexLightData.volumeOff1;
  IconData get rightSquare => _IconexLightData.rightSquare;
  IconData get download2 => _IconexLightData.download2;
  IconData get downRight => _IconexLightData.downRight;
  IconData get calculator => _IconexLightData.calculator;
  IconData get mouse => _IconexLightData.mouse;
  IconData get zoomOut => _IconexLightData.zoomOut;
  IconData get graph => _IconexLightData.graph;
  IconData get folder => _IconexLightData.folder;
  IconData get volumeOff3 => _IconexLightData.volumeOff3;
  IconData get users => _IconexLightData.users;
  IconData get left => _IconexLightData.left;
  IconData get timer => _IconexLightData.timer;
  IconData get gamepad => _IconexLightData.gamepad;
  IconData get minus => _IconexLightData.minus;
  IconData get downLeftCircle => _IconexLightData.downLeftCircle;
  IconData get documentDelete => _IconexLightData.documentDelete;
  IconData get swap => _IconexLightData.swap;
  IconData get volumeOff2 => _IconexLightData.volumeOff2;
  IconData get heart => _IconexLightData.heart;
}

class _IconexBroken {
  const _IconexBroken();

  IconData get infoSquare => _IconexBrokenData.infoSquare;
  IconData get lightning => _IconexBrokenData.lightning;
  IconData get search => _IconexBrokenData.search;
  IconData get timeSquare => _IconexBrokenData.timeSquare;
  IconData get receipt => _IconexBrokenData.receipt;
  IconData get leftCircle => _IconexBrokenData.leftCircle;
  IconData get figma => _IconexBrokenData.figma;
  IconData get upRightCircle => _IconexBrokenData.upRightCircle;
  IconData get shield2 => _IconexBrokenData.shield2;
  IconData get box1 => _IconexBrokenData.box1;
  IconData get chart1 => _IconexBrokenData.chart1;
  IconData get lockCheck => _IconexBrokenData.lockCheck;
  IconData get downLeft => _IconexBrokenData.downLeft;
  IconData get bag1 => _IconexBrokenData.bag1;
  IconData get bag3 => _IconexBrokenData.bag3;
  IconData get chart => _IconexBrokenData.chart;
  IconData get box2 => _IconexBrokenData.box2;
  IconData get shield1 => _IconexBrokenData.shield1;
  IconData get user => _IconexBrokenData.user;
  IconData get bag2 => _IconexBrokenData.bag2;
  IconData get volumeUp => _IconexBrokenData.volumeUp;
  IconData get home => _IconexBrokenData.home;
  IconData get moreCircle => _IconexBrokenData.moreCircle;
  IconData get category2 => _IconexBrokenData.category2;
  IconData get music => _IconexBrokenData.music;
  IconData get swap2 => _IconexBrokenData.swap2;
  IconData get logout => _IconexBrokenData.logout;
  IconData get upSquare => _IconexBrokenData.upSquare;
  IconData get right2 => _IconexBrokenData.right2;
  IconData get documentAdd => _IconexBrokenData.documentAdd;
  IconData get downSquare => _IconexBrokenData.downSquare;
  IconData get down => _IconexBrokenData.down;
  IconData get lockX => _IconexBrokenData.lockX;
  IconData get upRight => _IconexBrokenData.upRight;
  IconData get caseIcon => _IconexBrokenData.caseIcon;
  IconData get swap3 => _IconexBrokenData.swap3;
  IconData get creditCard => _IconexBrokenData.creditCard;
  IconData get vector => _IconexBrokenData.vector;
  IconData get cloudDownload => _IconexBrokenData.cloudDownload;
  IconData get messageCircle => _IconexBrokenData.messageCircle;
  IconData get downSquare2 => _IconexBrokenData.downSquare2;
  IconData get microphone => _IconexBrokenData.microphone;
  IconData get toggleRight => _IconexBrokenData.toggleRight;
  IconData get down2 => _IconexBrokenData.down2;
  IconData get zoomIn => _IconexBrokenData.zoomIn;
  IconData get rightSquare2 => _IconexBrokenData.rightSquare2;
  IconData get document2 => _IconexBrokenData.document2;
  IconData get upCircle1 => _IconexBrokenData.upCircle1;
  IconData get up => _IconexBrokenData.up;
  IconData get alarmClock => _IconexBrokenData.alarmClock;
  IconData get lock => _IconexBrokenData.lock;
  IconData get fire => _IconexBrokenData.fire;
  IconData get edit2 => _IconexBrokenData.edit2;
  IconData get link => _IconexBrokenData.link;
  IconData get key => _IconexBrokenData.key;
  IconData get cloudUpload => _IconexBrokenData.cloudUpload;
  IconData get settings => _IconexBrokenData.settings;
  IconData get cart => _IconexBrokenData.cart;
  IconData get edit1 => _IconexBrokenData.edit1;
  IconData get mail => _IconexBrokenData.mail;
  IconData get addUser => _IconexBrokenData.addUser;
  IconData get shield => _IconexBrokenData.shield;
  IconData get expand => _IconexBrokenData.expand;
  IconData get up2 => _IconexBrokenData.up2;
  IconData get upLeft => _IconexBrokenData.upLeft;
  IconData get upSquare2 => _IconexBrokenData.upSquare2;
  IconData get sale => _IconexBrokenData.sale;
  IconData get layers => _IconexBrokenData.layers;
  IconData get login => _IconexBrokenData.login;
  IconData get book => _IconexBrokenData.book;
  IconData get collapse => _IconexBrokenData.collapse;
  IconData get rightCircle => _IconexBrokenData.rightCircle;
  IconData get wallet => _IconexBrokenData.wallet;
  IconData get bell => _IconexBrokenData.bell;
  IconData get logout1 => _IconexBrokenData.logout1;
  IconData get coffee => _IconexBrokenData.coffee;
  IconData get flag => _IconexBrokenData.flag;
  IconData get trashCan => _IconexBrokenData.trashCan;
  IconData get stop => _IconexBrokenData.stop;
  IconData get category => _IconexBrokenData.category;
  IconData get plus => _IconexBrokenData.plus;
  IconData get document => _IconexBrokenData.document;
  IconData get filter1 => _IconexBrokenData.filter1;
  IconData get check => _IconexBrokenData.check;
  IconData get headphones => _IconexBrokenData.headphones;
  IconData get calling => _IconexBrokenData.calling;
  IconData get left2 => _IconexBrokenData.left2;
  IconData get downCircle1 => _IconexBrokenData.downCircle1;
  IconData get lockOpen => _IconexBrokenData.lockOpen;
  IconData get scale => _IconexBrokenData.scale;
  IconData get close => _IconexBrokenData.close;
  IconData get coupon2 => _IconexBrokenData.coupon2;
  IconData get callMissed => _IconexBrokenData.callMissed;
  IconData get copy => _IconexBrokenData.copy;
  IconData get burger => _IconexBrokenData.burger;
  IconData get coins => _IconexBrokenData.coins;
  IconData get volumeDown => _IconexBrokenData.volumeDown;
  IconData get hide => _IconexBrokenData.hide;
  IconData get infoCircle => _IconexBrokenData.infoCircle;
  IconData get image => _IconexBrokenData.image;
  IconData get leftSquare => _IconexBrokenData.leftSquare;
  IconData get save => _IconexBrokenData.save;
  IconData get callSilent => _IconexBrokenData.callSilent;
  IconData get leftSquare2 => _IconexBrokenData.leftSquare2;
  IconData get right => _IconexBrokenData.right;
  IconData get coupon3 => _IconexBrokenData.coupon3;
  IconData get upLeftCircle => _IconexBrokenData.upLeftCircle;
  IconData get coupon1 => _IconexBrokenData.coupon1;
  IconData get leftCircle1 => _IconexBrokenData.leftCircle1;
  IconData get paperclip => _IconexBrokenData.paperclip;
  IconData get loading => _IconexBrokenData.loading;
  IconData get noSoundMicrophone => _IconexBrokenData.noSoundMicrophone;
  IconData get moreSquare => _IconexBrokenData.moreSquare;
  IconData get play => _IconexBrokenData.play;
  IconData get downRightCircle => _IconexBrokenData.downRightCircle;
  IconData get send => _IconexBrokenData.send;
  IconData get camera => _IconexBrokenData.camera;
  IconData get toggleLeft => _IconexBrokenData.toggleLeft;
  IconData get upCircle => _IconexBrokenData.upCircle;
  IconData get star => _IconexBrokenData.star;
  IconData get downCircle => _IconexBrokenData.downCircle;
  IconData get danger => _IconexBrokenData.danger;
  IconData get browser => _IconexBrokenData.browser;
  IconData get messageSquare => _IconexBrokenData.messageSquare;
  IconData get compass => _IconexBrokenData.compass;
  IconData get basketball => _IconexBrokenData.basketball;
  IconData get musicPlate => _IconexBrokenData.musicPlate;
  IconData get call => _IconexBrokenData.call;
  IconData get link2 => _IconexBrokenData.link2;
  IconData get eye => _IconexBrokenData.eye;
  IconData get location => _IconexBrokenData.location;
  IconData get rightCircle1 => _IconexBrokenData.rightCircle1;
  IconData get gift => _IconexBrokenData.gift;
  IconData get colorPalette => _IconexBrokenData.colorPalette;
  IconData get share => _IconexBrokenData.share;
  IconData get video => _IconexBrokenData.video;
  IconData get filter => _IconexBrokenData.filter;
  IconData get oldschoolGamepad => _IconexBrokenData.oldschoolGamepad;
  IconData get calendar => _IconexBrokenData.calendar;
  IconData get laptop => _IconexBrokenData.laptop;
  IconData get heartbeat => _IconexBrokenData.heartbeat;
  IconData get scanner => _IconexBrokenData.scanner;
  IconData get cloud => _IconexBrokenData.cloud;
  IconData get pause => _IconexBrokenData.pause;
  IconData get bookmark => _IconexBrokenData.bookmark;
  IconData get rocket => _IconexBrokenData.rocket;
  IconData get screen => _IconexBrokenData.screen;
  IconData get iphone => _IconexBrokenData.iphone;
  IconData get volumeOff1 => _IconexBrokenData.volumeOff1;
  IconData get rightSquare => _IconexBrokenData.rightSquare;
  IconData get download2 => _IconexBrokenData.download2;
  IconData get downRight => _IconexBrokenData.downRight;
  IconData get calculator => _IconexBrokenData.calculator;
  IconData get mouse => _IconexBrokenData.mouse;
  IconData get zoomOut => _IconexBrokenData.zoomOut;
  IconData get graph => _IconexBrokenData.graph;
  IconData get folder => _IconexBrokenData.folder;
  IconData get users => _IconexBrokenData.users;
  IconData get left => _IconexBrokenData.left;
  IconData get timer => _IconexBrokenData.timer;
  IconData get gamepad => _IconexBrokenData.gamepad;
  IconData get minus => _IconexBrokenData.minus;
  IconData get downLeftCircle => _IconexBrokenData.downLeftCircle;
  IconData get documentDelete => _IconexBrokenData.documentDelete;
  IconData get swap => _IconexBrokenData.swap;
  IconData get volumeOff2 => _IconexBrokenData.volumeOff2;
  IconData get heart => _IconexBrokenData.heart;
}
